sudo: false

language: node_js

node_js:
  - lts/*

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  yarn: true

script:
  - yarn lint
  - yarn build

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
